# Importing Neccesary Libraries

In [60]:
pip install pymysql

Requirement already satisfied: pymysql in c:\users\arvind\appdata\local\programs\python\python310\lib\site-packages (1.1.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [61]:
import pandas as pd
from sqlalchemy import create_engine
import pymysql

# Importing games Dataset

In [2]:
df1 = pd.read_csv('games.csv')

In [3]:
df1.head()

,Unnamed: 0,Title,Release Date,Team,Rating,Times Listed,Number of Reviews,Genres,Summary,Reviews,Plays,Playing,Backlogs,Wishlist
0,0,Elden Ring,"Feb 25, 2022","['Bandai Namco Entertainment', 'FromSoftware']",4.5,3.9K,3.9K,"['Adventure', 'RPG']","Elden Ring is a fantasy, action and open world...","[""The first playthrough of elden ring is one o...",17K,3.8K,4.6K,4.8K
1,1,Hades,"Dec 10, 2019",['Supergiant Games'],4.3,2.9K,2.9K,"['Adventure', 'Brawler', 'Indie', 'RPG']",A rogue-lite hack and slash dungeon crawler in...,['convinced this is a roguelike for people who...,21K,3.2K,6.3K,3.6K
2,2,The Legend of Zelda: Breath of the Wild,"Mar 03, 2017","['Nintendo', 'Nintendo EPD Production Group No...",4.4,4.3K,4.3K,"['Adventure', 'RPG']",The Legend of Zelda: Breath of the Wild is the...,['This game is the game (that is not CS:GO) th...,30K,2.5K,5K,2.6K
3,3,Undertale,"Sep 15, 2015","['tobyfox', '8-4']",4.2,3.5K,3.5K,"['Adventure', 'Indie', 'RPG', 'Turn Based Stra...","A small child falls into the Underground, wher...",['soundtrack is tied for #1 with nier automata...,28K,679,4.9K,1.8K
4,4,Hollow Knight,"Feb 24, 2017",['Team Cherry'],4.4,3K,3K,"['Adventure', 'Indie', 'Platform']",A 2D metroidvania with an emphasis on close co...,"[""this games worldbuilding is incredible, with...",21K,2.4K,8.3K,2.3K

# Data Preproccessing

In [4]:
df1.shape

(1512, 14)

In [5]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1512 entries, 0 to 1511
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         1512 non-null   int64
 1   Title              1512 non-null   object
 2   Release Date       1512 non-null   object
 3   Team               1511 non-null   object
 4   Rating             1499 non-null   float64
 5   Times Listed       1512 non-null   object
 6   Number of Reviews  1512 non-null   object
 7   Genres             1512 non-null   object
 8   Summary            1511 non-null   object
 9   Reviews            1512 non-null   object
 10  Plays              1512 non-null   object
 11  Playing            1512 non-null   object
 12  Backlogs           1512 non-null   object
 13  Wishlist           1512 non-null   object
dtypes: float64(1), int64(1), object(12)
memory usage: 165.5+ KB

## Treating Null Values and duplicates

In [6]:
df1.isna().sum()

Unnamed: 0            0
Title                 0
Release Date          0
Team                  1
Rating               13
Times Listed          0
Number of Reviews     0
Genres                0
Summary               1
Reviews               0
Plays                 0
Playing               0
Backlogs              0
Wishlist              0
dtype: int64

In [7]:
df1.duplicated().sum()

np.int64(0)

In [8]:
df1.dropna(subset=['Team'], inplace=True)

In [9]:
df1['Rating'] = df1['Rating'].fillna(df1['Rating'].mean())

## Remmoving Unneccesary Columns

In [10]:
df1.drop(columns=['Summary', 'Unnamed: 0'], inplace=True)

In [11]:
df1.drop(columns = ['Reviews'], inplace = True)

In [12]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1511 entries, 0 to 1511
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Title              1511 non-null   object
 1   Release Date       1511 non-null   object
 2   Team               1511 non-null   object
 3   Rating             1511 non-null   float64
 4   Times Listed       1511 non-null   object
 5   Number of Reviews  1511 non-null   object
 6   Genres             1511 non-null   object
 7   Plays              1511 non-null   object
 8   Playing            1511 non-null   object
 9   Backlogs           1511 non-null   object
 10  Wishlist           1511 non-null   object
dtypes: float64(1), object(10)
memory usage: 141.7+ KB

In [13]:
df1.head()

,Title,Release Date,Team,Rating,Times Listed,Number of Reviews,Genres,Plays,Playing,Backlogs,Wishlist
0,Elden Ring,"Feb 25, 2022","['Bandai Namco Entertainment', 'FromSoftware']",4.5,3.9K,3.9K,"['Adventure', 'RPG']",17K,3.8K,4.6K,4.8K
1,Hades,"Dec 10, 2019",['Supergiant Games'],4.3,2.9K,2.9K,"['Adventure', 'Brawler', 'Indie', 'RPG']",21K,3.2K,6.3K,3.6K
2,The Legend of Zelda: Breath of the Wild,"Mar 03, 2017","['Nintendo', 'Nintendo EPD Production Group No...",4.4,4.3K,4.3K,"['Adventure', 'RPG']",30K,2.5K,5K,2.6K
3,Undertale,"Sep 15, 2015","['tobyfox', '8-4']",4.2,3.5K,3.5K,"['Adventure', 'Indie', 'RPG', 'Turn Based Stra...",28K,679,4.9K,1.8K
4,Hollow Knight,"Feb 24, 2017",['Team Cherry'],4.4,3K,3K,"['Adventure', 'Indie', 'Platform']",21K,2.4K,8.3K,2.3K

# Text Preproccesing

## Spliting the 'genres' and 'team' column

In [14]:
df1['Genres'] = df1['Genres'].str.replace('[\[\]\']', '', regex=True).str.split(',')
df1 = df1.explode('Genres')

In [15]:
df1['Team'] = df1['Team'].str.replace('[\[\]\']', '', regex=True).str.split(',')
df1 = df1.explode('Team')

## Converting the 'K' for the values in the rows for a particular column by multiplying by 1000

In [16]:
cols = ['Times Listed', 'Number of Reviews', 'Plays', 'Playing', 'Backlogs', 'Wishlist']
for col in cols:
  if df1[col].astype(str).str.contains('K').any():
    df1[col] = df1[col].astype(str).str.replace('K', '', regex=False)
    df1[col] = pd.to_numeric(df1[col]) * 1000

display(df1.head())

for col in cols:
  df1[col] = df1[col].astype(int)

,Title,Release Date,Team,Rating,Times Listed,Number of Reviews,Genres,Plays,Playing,Backlogs,Wishlist
0,Elden Ring,"Feb 25, 2022",Bandai Namco Entertainment,4.5,3900.0,3900.0,Adventure,17000.0,3800.0,4600.0,4800.0
0,Elden Ring,"Feb 25, 2022",FromSoftware,4.5,3900.0,3900.0,Adventure,17000.0,3800.0,4600.0,4800.0
0,Elden Ring,"Feb 25, 2022",Bandai Namco Entertainment,4.5,3900.0,3900.0,RPG,17000.0,3800.0,4600.0,4800.0
0,Elden Ring,"Feb 25, 2022",FromSoftware,4.5,3900.0,3900.0,RPG,17000.0,3800.0,4600.0,4800.0
1,Hades,"Dec 10, 2019",Supergiant Games,4.3,2900.0,2900.0,Adventure,21000.0,3200.0,6300.0,3600.0

## Convert the release date into datetime value

In [17]:
df1['Release Date'] = pd.to_datetime(df1['Release Date'], errors='coerce')

In [18]:
df1

,Title,Release Date,Team,Rating,Times Listed,Number of Reviews,Genres,Plays,Playing,Backlogs,Wishlist
0,Elden Ring,2022-02-25,Bandai Namco Entertainment,4.5,3900,3900,Adventure,17000,3800,4600,4800
0,Elden Ring,2022-02-25,FromSoftware,4.5,3900,3900,Adventure,17000,3800,4600,4800
0,Elden Ring,2022-02-25,Bandai Namco Entertainment,4.5,3900,3900,RPG,17000,3800,4600,4800
0,Elden Ring,2022-02-25,FromSoftware,4.5,3900,3900,RPG,17000,3800,4600,4800
1,Hades,2019-12-10,Supergiant Games,4.3,2900,2900,Adventure,21000,3200,6300,3600
...,...,...,...,...,...,...,...,...,...,...,...
1510,Baldur's Gate 3,2020-10-06,Larian Studios,4.1,165000,165000,Turn Based Strategy,269000,79000,388000,602000
1511,The LEGO Movie Videogame,2014-02-04,WB Games,2.8,184000,184000,Adventure,1700,11000,239000,73000
1511,The LEGO Movie Videogame,2014-02-04,TT Fusion,2.8,184000,184000,Adventure,1700,11000,239000,73000
1511,The LEGO Movie Videogame,2014-02-04,WB Games,2.8,184000,184000,Puzzle,1700,11000,239000,73000
1511,The LEGO Movie Videogame,2014-02-04,TT Fusion,2.8,184000,184000,Puzzle,1700,11000,239000,73000

# Data Pre-proccesing - II

In [19]:
df1.isna().sum()

Title                 0
Release Date         11
Team                  0
Rating                0
Times Listed          0
Number of Reviews     0
Genres                0
Plays                 0
Playing               0
Backlogs              0
Wishlist              0
dtype: int64

In [20]:
df1.dropna(subset=['Release Date'], inplace=True)

In [21]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6618 entries, 0 to 1511
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Title              6618 non-null   object
 1   Release Date       6618 non-null   datetime64[ns]
 2   Team               6618 non-null   object
 3   Rating             6618 non-null   float64
 4   Times Listed       6618 non-null   int64
 5   Number of Reviews  6618 non-null   int64
 6   Genres             6618 non-null   object
 7   Plays              6618 non-null   int64
 8   Playing            6618 non-null   int64
 9   Backlogs           6618 non-null   int64
 10  Wishlist           6618 non-null   int64
dtypes: datetime64[ns](1), float64(1), int64(6), object(3)
memory usage: 620.4+ KB

In [22]:
df1.duplicated().sum()

np.int64(1750)

In [23]:
df1.drop_duplicates(inplace=True)

In [24]:
df1.duplicated().sum()

np.int64(0)

In [25]:
df1.isna().sum()

Title                0
Release Date         0
Team                 0
Rating               0
Times Listed         0
Number of Reviews    0
Genres               0
Plays                0
Playing              0
Backlogs             0
Wishlist             0
dtype: int64

# Saving the preproccessed games data

In [26]:
df1.to_csv('games_cleaned.csv', index=False)

# Loading the sales Data

In [28]:
df2 = pd.read_csv('vgsales.csv')
df2.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37

# Data Preproccessing

In [29]:
df2.shape

(16598, 11)

In [30]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16598 entries, 0 to 16597
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Rank          16598 non-null  int64
 1   Name          16598 non-null  object
 2   Platform      16598 non-null  object
 3   Year          16327 non-null  float64
 4   Genre         16598 non-null  object
 5   Publisher     16540 non-null  object
 6   NA_Sales      16598 non-null  float64
 7   EU_Sales      16598 non-null  float64
 8   JP_Sales      16598 non-null  float64
 9   Other_Sales   16598 non-null  float64
 10  Global_Sales  16598 non-null  float64
dtypes: float64(6), int64(1), object(4)
memory usage: 1.4+ MB

## Checking and Treating the null values and duplicates in the data

In [31]:
df2.isna().sum()

Rank              0
Name              0
Platform          0
Year            271
Genre             0
Publisher        58
NA_Sales          0
EU_Sales          0
JP_Sales          0
Other_Sales       0
Global_Sales      0
dtype: int64

In [32]:
df2.duplicated().sum()

np.int64(0)

In [33]:
df2.dropna(subset=['Year', 'Publisher'], inplace=True)

In [34]:
df2.isna().sum()

Rank            0
Name            0
Platform        0
Year            0
Genre           0
Publisher       0
NA_Sales        0
EU_Sales        0
JP_Sales        0
Other_Sales     0
Global_Sales    0
dtype: int64

## Converting year column to datetime types

In [35]:
df2['Year'] = df2['Year'].astype(int)

In [36]:
df2['Year'] = pd.to_datetime(df2['Year'], format='%Y')

In [37]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16291 entries, 0 to 16597
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Rank          16291 non-null  int64
 1   Name          16291 non-null  object
 2   Platform      16291 non-null  object
 3   Year          16291 non-null  datetime64[ns]
 4   Genre         16291 non-null  object
 5   Publisher     16291 non-null  object
 6   NA_Sales      16291 non-null  float64
 7   EU_Sales      16291 non-null  float64
 8   JP_Sales      16291 non-null  float64
 9   Other_Sales   16291 non-null  float64
 10  Global_Sales  16291 non-null  float64
dtypes: datetime64[ns](1), float64(5), int64(1), object(4)
memory usage: 1.5+ MB

In [38]:
df2.isna().sum()

Rank            0
Name            0
Platform        0
Year            0
Genre           0
Publisher       0
NA_Sales        0
EU_Sales        0
JP_Sales        0
Other_Sales     0
Global_Sales    0
dtype: int64

In [39]:
df2.duplicated().sum()

np.int64(0)

# Saving the preproccesed sales Data

In [40]:
df2.to_csv('vgsales_cleaned.csv', index=False)

# Merging the Preproccessed Datasets

In [42]:
import pandas as pd
games = pd.read_csv('games_cleaned.csv')
vgsales = pd.read_csv('vgsales_cleaned.csv')

In [43]:
games.head()

,Title,Release Date,Team,Rating,Times Listed,Number of Reviews,Genres,Plays,Playing,Backlogs,Wishlist
0,Elden Ring,2022-02-25,Bandai Namco Entertainment,4.5,3900,3900,Adventure,17000,3800,4600,4800
1,Elden Ring,2022-02-25,FromSoftware,4.5,3900,3900,Adventure,17000,3800,4600,4800
2,Elden Ring,2022-02-25,Bandai Namco Entertainment,4.5,3900,3900,RPG,17000,3800,4600,4800
3,Elden Ring,2022-02-25,FromSoftware,4.5,3900,3900,RPG,17000,3800,4600,4800
4,Hades,2019-12-10,Supergiant Games,4.3,2900,2900,Adventure,21000,3200,6300,3600

In [44]:
vgsales.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006-01-01,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985-01-01,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008-01-01,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009-01-01,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996-01-01,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37

In [45]:
merged_df = pd.merge(df1, df2, left_on='Title', right_on='Name', how='inner')

In [46]:
display(merged_df.head())
display(merged_df.shape)

,Title,Release Date,Team,Rating,Times Listed,Number of Reviews,Genres,Plays,Playing,Backlogs,...,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,Minecraft,2011-11-18,Mojang Studios,4.3,2300,2300,Adventure,33000,1800,1100,...,Minecraft,X360,2013-01-01,Misc,Microsoft Game Studios,5.58,2.83,0.02,0.77,9.20
1,Minecraft,2011-11-18,Mojang Studios,4.3,2300,2300,Adventure,33000,1800,1100,...,Minecraft,PS3,2014-01-01,Misc,Sony Computer Entertainment,1.97,2.51,0.00,0.94,5.42
2,Minecraft,2011-11-18,Mojang Studios,4.3,2300,2300,Adventure,33000,1800,1100,...,Minecraft,PS4,2014-01-01,Misc,Sony Computer Entertainment Europe,1.38,1.87,0.12,0.65,4.02
3,Minecraft,2011-11-18,Mojang Studios,4.3,2300,2300,Adventure,33000,1800,1100,...,Minecraft,XOne,2014-01-01,Misc,Microsoft Game Studios,1.43,0.76,0.00,0.22,2.41
4,Minecraft,2011-11-18,Mojang Studios,4.3,2300,2300,Adventure,33000,1800,1100,...,Minecraft,PSV,2014-01-01,Misc,Sony Computer Entertainment Europe,0.28,0.79,0.87,0.32,2.25

(3788, 22)

## Removing the unneccesary columns

In [47]:
merged_df.columns

Index(['Title', 'Release Date', 'Team', 'Rating', 'Times Listed',
       'Number of Reviews', 'Genres', 'Plays', 'Playing', 'Backlogs',
       'Wishlist', 'Rank', 'Name', 'Platform', 'Year', 'Genre', 'Publisher',
       'NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales'],
      dtype='object')

In [48]:
merged_df.drop(columns=['Name', 'Year', 'Genre'], inplace=True)

In [49]:
merged_df

,Title,Release Date,Team,Rating,Times Listed,Number of Reviews,Genres,Plays,Playing,Backlogs,Wishlist,Rank,Platform,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,Minecraft,2011-11-18,Mojang Studios,4.3,2300,2300,Adventure,33000,1800,1100,230000,73,X360,Microsoft Game Studios,5.58,2.83,0.02,0.77,9.20
1,Minecraft,2011-11-18,Mojang Studios,4.3,2300,2300,Adventure,33000,1800,1100,230000,169,PS3,Sony Computer Entertainment,1.97,2.51,0.00,0.94,5.42
2,Minecraft,2011-11-18,Mojang Studios,4.3,2300,2300,Adventure,33000,1800,1100,230000,298,PS4,Sony Computer Entertainment Europe,1.38,1.87,0.12,0.65,4.02
3,Minecraft,2011-11-18,Mojang Studios,4.3,2300,2300,Adventure,33000,1800,1100,230000,644,XOne,Microsoft Game Studios,1.43,0.76,0.00,0.22,2.41
4,Minecraft,2011-11-18,Mojang Studios,4.3,2300,2300,Adventure,33000,1800,1100,230000,715,PSV,Sony Computer Entertainment Europe,0.28,0.79,0.87,0.32,2.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3783,The LEGO Movie Videogame,2014-02-04,TT Fusion,2.8,184000,184000,Puzzle,1700,11000,239000,73000,3030,PS4,Warner Bros. Interactive Entertainment,0.24,0.31,0.01,0.11,0.67
3784,The LEGO Movie Videogame,2014-02-04,TT Fusion,2.8,184000,184000,Puzzle,1700,11000,239000,73000,3056,WiiU,Warner Bros. Interactive Entertainment,0.35,0.23,0.03,0.06,0.66
3785,The LEGO Movie Videogame,2014-02-04,TT Fusion,2.8,184000,184000,Puzzle,1700,11000,239000,73000,3884,XOne,Warner Bros. Interactive Entertainment,0.34,0.13,0.00,0.04,0.51
3786,The LEGO Movie Videogame,2014-02-04,TT Fusion,2.8,184000,184000,Puzzle,1700,11000,239000,73000,4734,PSV,Warner Bros. Interactive Entertainment,0.05,0.26,0.00,0.09,0.41
3787,The LEGO Movie Videogame,2014-02-04,TT Fusion,2.8,184000,184000,Puzzle,1700,11000,239000,73000,12266,PC,Warner Bros. Interactive Entertainment,0.02,0.04,0.00,0.01,0.06

# Checking for null values and duplicates in the merged dataset

In [50]:
merged_df.isna().sum()

Title                0
Release Date         0
Team                 0
Rating               0
Times Listed         0
Number of Reviews    0
Genres               0
Plays                0
Playing              0
Backlogs             0
Wishlist             0
Rank                 0
Platform             0
Publisher            0
NA_Sales             0
EU_Sales             0
JP_Sales             0
Other_Sales          0
Global_Sales         0
dtype: int64

In [51]:
merged_df.duplicated().sum()

np.int64(0)

# Saving the merged dataset

In [52]:
merged_df.to_csv('merged_games_sales.csv', index=False)

# Creating a database in MySQL and storing all the preproccessed datasets in the database

In [55]:
try:
    con = pymysql.connect(
        host="localhost",
        user="root",
        password="Arvind@2003",
        autocommit=True
    )
    cursor = con.cursor()
    cursor.execute("CREATE DATABASE IF NOT EXISTS Video_Games_Database;")
    print("✅ Database created successfully!")

except Exception as e:
    print("❌ Error:", e)

✅ Database created successfully!

In [56]:
mycursor=con.cursor()

In [57]:
mycursor.execute("SHOW DATABASES")
for x in mycursor:
    print(x)

('books_data',)
('food_wastage_management',)
('information_schema',)
('insurance',)
('my_new_database',)
('mysql',)
('parks_and_recreation',)
('performance_schema',)
('sakila',)
('sys',)
('vg_sales',)
('video_games_database',)

In [59]:
import pandas as pd
from sqlalchemy import create_engine

# ✅ 1. Connection engine (note the encoded @ → %40)
engine = create_engine("mysql+pymysql://root:Arvind%402003@localhost/Video_Games_Database")

# ✅ 2. Dataset dictionary
datasets = {
    'games': 'games_cleaned.csv',
    'sales': 'vgsales_cleaned.csv',
    'merged_sales_games': 'merged_games_sales.csv',
}

# ✅ 3. Upload loop
for table_name, file_path in datasets.items():
    try:
        df = pd.read_csv(file_path)
        df.to_sql(
            name=table_name,
            con=engine,
            if_exists='replace',
            index=False
        )
        print(f"✅ Successfully uploaded '{file_path}' as table '{table_name}'")

    except Exception as e:
        print(f"❌ Error uploading {file_path}: {e}")

print("🎉 All datasets processed!")

✅ Successfully uploaded 'games_cleaned.csv' as table 'games'
✅ Successfully uploaded 'vgsales_cleaned.csv' as table 'sales'
✅ Successfully uploaded 'merged_games_sales.csv' as table 'merged_sales_games'
🎉 All datasets processed!